version: '3.8'

services:
  graylog:
    image: graylog/graylog:5.2
    env_file: .env
    ports:
      - "9000:9000"
      - "12201:12201"
    depends_on:
      - mongodb
      - elasticsearch
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  mongo_data:
  es_data:
