version: '3.8'

services:
  zulip:
    image: zulip/zulip:latest
    env_file: .env
    ports:
      - "9991:9991"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres:13
    env_file: .env
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    env_file: .env
    restart: unless-stopped
