version: '3.8'

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo_data:
